import { ATOM, CONCAT, OPTIONAL, OR, STAR, WORD } from "../..";
import { DECLARATOR } from "../declarator";
import {
  CLOSING_PARENTHESIS,
  EXPRESSION,
  OPENING_PARENTHESIS,
} from "./expression";
import { IDENTIFIER } from "../identifier";
import {
  ASSIGNMENT_OPERATOR,
  ASSIGNMENT_OPERATORS,
} from "../operator/assignment";
import { SEMICOLON } from "../specialCharacter";
import { VALUE } from "../value";
import { NON_EMPTY_WHITESPACE, WHITESPACE } from "../whitespace";
import { DATATYPE_SPECIFIER } from "../keyword";
import { COMMENT } from "../comment";

let _STATEMENTS = OR().name("STATEMENTS");

const LIST_OF_STATEMENTS = STAR(CONCAT(WHITESPACE, _STATEMENTS, WHITESPACE));

export const CODE_BLOCK = CONCAT(
  ATOM("{").name("OPENING_CURLY"),
  LIST_OF_STATEMENTS,
  ATOM("}").name("CLOSING_CURLY")
).name("CODE_BLOCK");

export const DECLARATION_STATEMENT = CONCAT(
  DECLARATOR,
  NON_EMPTY_WHITESPACE,
  OPTIONAL(CONCAT(DATATYPE_SPECIFIER, NON_EMPTY_WHITESPACE)),
  IDENTIFIER,
  WHITESPACE,
  ASSIGNMENT_OPERATOR,
  WHITESPACE,
  EXPRESSION
).name("DECLARATION_STATEMENT");

export const ASSIGNMENT_STATEMENT = CONCAT(
  IDENTIFIER,
  WHITESPACE,
  ASSIGNMENT_OPERATORS,
  WHITESPACE,
  EXPRESSION
).name("ASSIGNMENT_STATEMENT");

export const ELSE_IF_STATEMENT = CONCAT(
  WORD("else if").name("IF").token(),
  WHITESPACE,
  OPENING_PARENTHESIS,
  WHITESPACE,
  EXPRESSION,
  WHITESPACE,
  CLOSING_PARENTHESIS,
  WHITESPACE,
  CODE_BLOCK
);

export const ELSE_STATEMENT = CONCAT(
  WORD("else").name("IF").token(),
  WHITESPACE,
  CODE_BLOCK
);

export const WHILE_STATEMENT = CONCAT(
  WORD("while").name("WHILE").token(),
  WHITESPACE,
  OPENING_PARENTHESIS,
  WHITESPACE,
  EXPRESSION,
  WHITESPACE,
  CLOSING_PARENTHESIS,
  WHITESPACE,
  CODE_BLOCK
);

export const IF_STATEMENT = CONCAT(
  WORD("if").name("IF").token(),
  WHITESPACE,
  OPENING_PARENTHESIS,
  WHITESPACE,
  EXPRESSION,
  WHITESPACE,
  CLOSING_PARENTHESIS,
  WHITESPACE,
  CODE_BLOCK,
  OPTIONAL(STAR(CONCAT(WHITESPACE, ELSE_IF_STATEMENT, WHITESPACE))),
  OPTIONAL(CONCAT(WHITESPACE, ELSE_STATEMENT, WHITESPACE))
);

export const DO_WHILE_STATEMENT = CONCAT(
  WORD("do").name("DO").token(),
  WHITESPACE,
  CODE_BLOCK,
  WHITESPACE,
  WORD("while").name("WHILE").token(),
  WHITESPACE,
  OPENING_PARENTHESIS,
  WHITESPACE,
  EXPRESSION,
  WHITESPACE,
  CLOSING_PARENTHESIS,
  WHITESPACE,
  SEMICOLON
);

const TRUE_STATEMENTS = OR(
  DECLARATION_STATEMENT,
  ASSIGNMENT_STATEMENT,
  EXPRESSION
).name("STATEMENTS");

export const FOR_STATEMENT = CONCAT(
  WORD("for").name("FOR").token(),
  WHITESPACE,
  OPENING_PARENTHESIS,
  WHITESPACE,
  TRUE_STATEMENTS,
  WHITESPACE,
  SEMICOLON,
  WHITESPACE,
  TRUE_STATEMENTS,
  WHITESPACE,
  SEMICOLON,
  WHITESPACE,
  TRUE_STATEMENTS,
  WHITESPACE,
  CLOSING_PARENTHESIS,
  WHITESPACE,
  CODE_BLOCK
);

export const FUNCTION_STATEMENT = CONCAT(
  WORD("function").name("FUNCTION").token(),
  NON_EMPTY_WHITESPACE,
  IDENTIFIER,
  WHITESPACE,
  OPENING_PARENTHESIS,
  WHITESPACE,
  STAR(
    CONCAT(
      IDENTIFIER,
      WHITESPACE,
      ATOM(",").name("PARAMETER_SEPARATOR"),
      WHITESPACE
    )
  ).name("REST_PARAMETER"),
  OPTIONAL(IDENTIFIER).name("PARAMETER").token(),
  WHITESPACE,
  CLOSING_PARENTHESIS,
  WHITESPACE,
  CODE_BLOCK
);

// @ts-ignore
_STATEMENTS = _STATEMENTS.OR(
  CONCAT(
    OPTIONAL(
      OR(
        CONCAT(TRUE_STATEMENTS, SEMICOLON).name("STATEMENTS"),
        IF_STATEMENT,
        FOR_STATEMENT,
        WHILE_STATEMENT,
        DO_WHILE_STATEMENT,
        FUNCTION_STATEMENT,
        CODE_BLOCK
      )
    ),
    OPTIONAL(CONCAT(WHITESPACE, COMMENT))
  )
);

export const SWISS = LIST_OF_STATEMENTS;
