import { ATOM, OR, WORD } from "../..";

//Assignment Operators (=, +=, -=, *=, /=, %=, //=, **=)
export const ASSIGNMENT_OPERATOR = ATOM("=")
  .name("ASSIGNMENT_OPERATOR")
  .token();

export const ADDITION_ASSIGNMENT_OPERATOR = WORD("+=")
  .name("ADDITION_ASSIGNMENT_OPERATOR")
  .token();

export const SUBTRACTION_ASSIGNMENT_OPERATOR = WORD("-=")
  .name("SUBTRACTION_ASSIGNMENT_OPERATOR")
  .token();

export const MULTIPLICATION_ASSIGNMENT_OPERATOR = WORD("*=")
  .name("MULTIPLICATION_ASSIGNMENT_OPERATOR")
  .token();

export const DIVISION_ASSIGNMENT_OPERATOR = WORD("/=")
  .name("DIVISION_ASSIGNMENT_OPERATOR")
  .token();

export const MODULO_ASSIGNMENT_OPERATOR = WORD("%=")
  .name("MODULO_ASSIGNMENT_OPERATOR")
  .token();

export const INTEGER_DIVISION_ASSIGNMENT_OPERATOR = WORD("//=")
  .name("INTEGER_DIVISION_ASSIGNMENT_OPERATOR")
  .token();

export const EXPONENT_ASSIGNMENT_OPERATOR = WORD("**=")
  .name("EXPONENT_ASSIGNMENT_OPERATOR")
  .token();

export const ASSIGNMENT_OPERATORS = OR(
  ASSIGNMENT_OPERATOR,
  ADDITION_ASSIGNMENT_OPERATOR,
  SUBTRACTION_ASSIGNMENT_OPERATOR,
  EXPONENT_ASSIGNMENT_OPERATOR,
  MULTIPLICATION_ASSIGNMENT_OPERATOR,
  INTEGER_DIVISION_ASSIGNMENT_OPERATOR,
  DIVISION_ASSIGNMENT_OPERATOR,
  MODULO_ASSIGNMENT_OPERATOR
).name("ASSIGNMENT_OPERATORS");
